{{- if .Values.ingress.enabled -}}
{{- $issuer := index .Values "ingress" "labels" "cert-manager.io/cluster-issuer" }}
{{- range .Values.ingress.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .secretName }}
spec:
  secretName: {{ .secretName }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ $issuer }}
  commonName: {{ first .hosts }}
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
---
{{- end }}
{{- end }}
