apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:
  - name: shell
    image: alpine
    command:
    - cat
    tty: true
  - name: node
    image: node:18.16.0-slim
    envFrom:
      - secretRef:
          name: balu-client-envs
    command:
      - cat
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - cat
    tty: true
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker/
  - name: helm
    image: alpine/helm
    command:
      - cat
    tty: true
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json
